[package]
name = "bomctl"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
structopt = "0.3.*"
lazy_static = "1.4.*"

[profile.release]
lto = true

[[bin]]
name = "bomctl"
